Attribute VB_Name = "Street_Name_Unabbreviator"
'=================================================================================================================================================
' This function works by going through a table that must be named "abbreviationsTable" with its upper left corner placed at Cell A1.
' The function then goes through all rows in the table and replaces each abbreviated word with its full form according to the select case below.
' To see the latest source code for this project, please visit https://github.com/theAwesomeFufuman/VBA-Street-Name-unabbreviator
'=================================================================================================================================================
Sub GeoCode()
    Range("A1").Activate
    Dim tbl As ListObject
    Dim x As Long
    Dim Address As String
    Dim AddrArray() As String
    Dim ModifiedAddr As String
    Dim SouthOrStreet As Integer
    Dim SaintOrStreet As Integer
    Dim EastOrE As Integer
    Set tbl = ActiveSheet.ListObjects("abbreviationsTable")
    'Loop Through Each DataBody Row in Table
    For x = 1 To tbl.ListRows.Count
        ActiveCell.Offset(1, 0).Activate
        AddrArray = Split(UCase(ActiveCell.Value), " ")
        For i = 0 To UBound(AddrArray)
            Select Case AddrArray(i)
                Case "ALLEE", "ALLY", "ALY"
                    AddrArray(i) = "ALLEY"
                Case "ANEX", "ANX"
                    AddrArray(i) = "ANNEX"
                Case "APT"
                    AddrArray(i) = "APARTMENT"
                Case "ARC"
                    AddrArray(i) = "ARCADE"
                Case "AV", "AVE", "AVE,", "AVE.", "AVEA", "AVEN", "AVENU", "AVN", "AVNUE"
                    AddrArray(i) = "AVENUE"
                Case "BSMT"
                    AddrArray(i) = "BASEMENT"
                Case "BAYOO", "BYU"
                    AddrArray(i) = "BAYOU"
                Case "BCH"
                    AddrArray(i) = "BEACH"
                Case "BND"
                    AddrArray(i) = "BEND"
                Case "BLF", "BLUF"
                    AddrArray(i) = "BLUFF"
                Case "BLFS"
                    AddrArray(i) = "BLUFFS"
                Case "BOT", "BOTTM", "BTM"
                    AddrArray(i) = "BOTTOM"
                Case "BLVD", "BOUL", "BOULV", "BVD"
                    AddrArray(i) = "BOULEVARD"
                Case "BR", "BRNCH"
                    AddrArray(i) = "BRANCH"
                Case "BRDGE", "BRG"
                    AddrArray(i) = "BRIDGE"
                Case "BDWY"
                    AddrArray(i) = "Broadway"
                Case "BRK"
                    AddrArray(i) = "BROOK"
                Case "BRKS"
                    AddrArray(i) = "BROOKS"
                Case "BLDG"
                    AddrArray(i) = "BUILDING"
                Case "BG"
                    AddrArray(i) = "BURG"
                Case "BGS"
                    AddrArray(i) = "BURGS"
                Case "BYP", "BYPA", "BYPAS", "BYPS"
                    AddrArray(i) = "BYPASS"
                Case "CMP", "CP"
                    AddrArray(i) = "CAMP"
                Case "CANYN", "CNYN", "CYN"
                    AddrArray(i) = "CANYON"
                Case "CPE"
                    AddrArray(i) = "CAPE"
                Case "CAUSWA", "CSWY"
                    AddrArray(i) = "CAUSEWAY"
                Case "CEN", "CENT", "CENTR", "CNTER", "CNTR", "CTR"
                    AddrArray(i) = "CENTER"
                Case "CTRS"
                    AddrArray(i) = "CENTERS"
                Case "CIR", "CIR.", "CIRC", "CIRCL", "CRCL", "CRCLE"
                    AddrArray(i) = "CIRCLE"
                Case "CIRS"
                    AddrArray(i) = "CIRCLES"
                Case "CCT"
                    AddrArray(i) = "Circuit"
                Case "CLF"
                    AddrArray(i) = "CLIFF"
                Case "CLFS"
                    AddrArray(i) = "CLIFFS"
                Case "Cl"
                    AddrArray(i) = "CLOSE"
                Case "CLB"
                    AddrArray(i) = "CLUB"
                Case "CMN"
                    AddrArray(i) = "COMMON"
                Case "CMNS"
                    AddrArray(i) = "COMMONS"
                Case "COR", "CRN"
                    AddrArray(i) = "CORNER"
                Case "CORS"
                    AddrArray(i) = "CORNERS"
                Case "CR", "C.R", "CR.", "C.R."
                    AddrArray(i) = "COUNTRY ROAD"
                Case "CRSE"
                    AddrArray(i) = "COURSE"
                Case "CT"
                    AddrArray(i) = "COURT"
                Case "CTS"
                    AddrArray(i) = "COURTS"
                Case "CV"
                    AddrArray(i) = "COVE"
                Case "CVS"
                    AddrArray(i) = "COVES"
                Case "CRK"
                    AddrArray(i) = "CREEK"
                Case "CRES", "CRSENT", "CRSNT"
                    AddrArray(i) = "CRESCENT"
                Case "CRST"
                    AddrArray(i) = "CREST"
                Case "CRSSNG", "XING"
                    AddrArray(i) = "CROSSING"
                Case "XRD"
                    AddrArray(i) = "CROSSROAD"
                Case "XRDS"
                    AddrArray(i) = "CROSSROADS"
                Case "CDS"
                    AddrArray(i) = "CUL-DE-SAC"
                Case "CURV"
                    AddrArray(i) = "CURVE"
                Case "DL"
                    AddrArray(i) = "DALE"
                Case "DM"
                    AddrArray(i) = "DAM"
                Case "DEPT"
                    AddrArray(i) = "DEPARTMENT"
                Case "DIV", "DV", "DVD"
                    AddrArray(i) = "DIVIDE"
                Case "DIRVE", "DR", "DR.", "DR,", "DRIV", "DRV"
                    AddrArray(i) = "DRIVE"
                Case "DRS"
                    AddrArray(i) = "DRIVES"
                Case "E"
                    EastOrE = MsgBox("Does the 'E' in the following address stand for 'East'? If no is selected, no change will be made." & vbCrLf & ActiveCell.Value, vbQuestion + vbYesNo + vbDefaultButton2, "East or E")
                    If EastOrE = vbYes Then
                        AddrArray(i) = "EAST"
                    End If
                Case "ESP"
                    AddrArray(i) = "ESPLANADE"
                Case "EST"
                    AddrArray(i) = "ESTATE"
                Case "ESTS"
                    AddrArray(i) = "ESTATES"
                Case "EXP", "EXPR", "EXPRESS", "EXPW", "EXPWY", "EXPY"
                    AddrArray(i) = "EXPRESSWAY"
                Case "EXT", "EXTN", "EXTNSN"
                    AddrArray(i) = "EXTENSION"
                Case "EXTS"
                    AddrArray(i) = "EXTENSIONS"
                Case "FLS"
                    AddrArray(i) = "FALLS"
                Case "FRRY", "FRY"
                    AddrArray(i) = "FERRY"
                Case "FLD"
                    AddrArray(i) = "FIELD"
                Case "FLDS"
                    AddrArray(i) = "FIELDS"
                Case "FLT"
                    AddrArray(i) = "FLAT"
                Case "FLTS"
                    AddrArray(i) = "FLATS"
                Case "FL"
                    AddrArray(i) = "FLOOR"
                Case "FM", "F.M", "FM.", "F.M."
                    AddrArray(i) = "FARM TO MARKET ROAD"
                Case "FRD"
                    AddrArray(i) = "FORD"
                Case "FRDS"
                    AddrArray(i) = "FORDS"
                Case "FRST"
                    AddrArray(i) = "FOREST"
                Case "FORG", "FRG"
                    AddrArray(i) = "FORGE"
                Case "FRGS"
                    AddrArray(i) = "FORGES"
                Case "FRK"
                    AddrArray(i) = "FORK"
                Case "FRKS"
                    AddrArray(i) = "FORKS"
                Case "FRT", "FT"
                    AddrArray(i) = "FORT"
                Case "FREEWY", "FRWAY", "FRWY", "FWY"
                    AddrArray(i) = "FREEWAY"
                Case "FRNT"
                    AddrArray(i) = "FRONT"
                Case "GARDN", "GDN", "GRDEN", "GRDN"
                    AddrArray(i) = "GARDEN"
                Case "GDNS", "GRDNS"
                    AddrArray(i) = "GARDENS"
                Case "GATEWY", "GATWAY", "GTWAY", "GTWY"
                    AddrArray(i) = "GATEWAY"
                Case "GLN"
                    AddrArray(i) = "GLEN"
                Case "GLNS"
                    AddrArray(i) = "GLENS"
                Case "GRN"
                    AddrArray(i) = "GREEN"
                Case "GRNS"
                    AddrArray(i) = "GREENS"
                Case "GR", "GROV", "GRV"
                    AddrArray(i) = "GROVE"
                Case "GRVS"
                    AddrArray(i) = "GROVES"
                Case "HNGR"
                    AddrArray(i) = "HANGER"
                Case "HARB", "HARBR", "HBR", "HRBOR"
                    AddrArray(i) = "HARBOR"
                Case "HBRS"
                    AddrArray(i) = "HARBORS"
                Case "HVN"
                    AddrArray(i) = "HAVEN"
                Case "HT"
                    AddrArray(i) = "HEIGHT"
                Case "HTS"
                    AddrArray(i) = "HEIGHTS"
                Case "HIGHWY", "HIWAY", "HIWY", "HWAY", "HWY"
                    AddrArray(i) = "HIGHWAY"
                Case "HL"
                    AddrArray(i) = "HILL"
                Case "HLS"
                    AddrArray(i) = "HILLS"
                Case "HLLW", "HOLW"
                    AddrArray(i) = "HOLLOW"
                Case "HOLWS"
                    AddrArray(i) = "HOLLOWS"
                Case "INFO"
                    AddrArray(i) = "INFORMATION"
                Case "INLT"
                    AddrArray(i) = "INLET"
                Case "INTL"
                    AddrArray(i) = "INTERNATIONAL"
                Case "IS", "ISL", "ISLND"
                    AddrArray(i) = "ISLAND"
                Case "ISLNDS", "ISS"
                    AddrArray(i) = "ISLANDS"
                Case "IL"
                    AddrArray(i) = "ISLE"
                Case "JCT", "JCTION", "JCTN", "JNC", "JUNCTN", "JUNCTON"
                    AddrArray(i) = "JUNCTION"
                Case "JCTNS", "JCTS"
                    AddrArray(i) = "JUNCTIONS"
                Case "KY"
                    AddrArray(i) = "KEY"
                Case "KYS"
                    AddrArray(i) = "KEYS"
                Case "KNL", "KNOL"
                    AddrArray(i) = "KNOLL"
                Case "KNLS"
                    AddrArray(i) = "KNOLLS"
                Case "LK"
                    AddrArray(i) = "LAKE"
                Case "LKS"
                    AddrArray(i) = "LAKES"
                Case "LNDG", "LNDNG"
                    AddrArray(i) = "LANDING"
                Case "LN"
                    AddrArray(i) = "LANE"
                Case "LGT"
                    AddrArray(i) = "LIGHT"
                Case "LGTS"
                    AddrArray(i) = "LIGHTS"
                Case "LF"
                    AddrArray(i) = "LOAF"
                Case "LBBY"
                    AddrArray(i) = "LOBBY"
                Case "LCK"
                    AddrArray(i) = "LOCK"
                Case "LCKS"
                    AddrArray(i) = "LOCKS"
                Case "LDG", "LDGE", "LODG"
                    AddrArray(i) = "LODGE"
                Case "LP"
                    AddrArray(i) = "LOOP"
                Case "LOWR"
                    AddrArray(i) = "LOWER"
                Case "MNR"
                    AddrArray(i) = "MANOR"
                Case "MNRS"
                    AddrArray(i) = "MANORS"
                Case "MDW"
                    AddrArray(i) = "MEADOW"
                Case "MDWS", "MEDOWS"
                    AddrArray(i) = "MEADOWS"
                Case "ML"
                    AddrArray(i) = "MILL"
                Case "MLS"
                    AddrArray(i) = "MILLS"
                Case "MISSN", "MSN", "MSSN"
                    AddrArray(i) = "MISSION"
                Case "MTWY"
                    AddrArray(i) = "MOTORWAY"
                Case "MNT", "MT"
                    AddrArray(i) = "MOUNT"
                Case "MNTAIN", "MNTN", "MOUNTIN", "MTIN", "MTN"
                    AddrArray(i) = "MOUNTAIN"
                Case "MNTNS", "MTNS"
                    AddrArray(i) = "MOUNTAINS"
                Case "NATL"
                    AddrArray(i) = "NATIONAL"
                Case "NCK"
                    AddrArray(i) = "NECK"
                Case "N"
                    AddrArray(i) = "NORTH"
                Case "NE"
                    AddrArray(i) = "NORTHEAST"
                Case "NW"
                    AddrArray(i) = "NORTHWEST"
                Case "OFC"
                    AddrArray(i) = "OFFICE"
                Case "ORCH", "ORCHRD"
                    AddrArray(i) = "ORCHARD"
                Case "OVL"
                    AddrArray(i) = "OVAL"
                Case "OPAS"
                    AddrArray(i) = "OVERPASS"
                Case "PDE"
                    AddrArray(i) = "PARADE"
                Case "PK", "PRK"
                    AddrArray(i) = "PARK"
                Case "PKS"
                    AddrArray(i) = "PARKS"
                Case "PARKWY", "PKWAY", "PKWY", "PKY"
                    AddrArray(i) = "PARKWAY"
                Case "PKWYS"
                    AddrArray(i) = "PARKWAYS"
                Case "PSGE"
                    AddrArray(i) = "PASSAGE"
                Case "PATH"
                    AddrArray(i) = "PATHS"
                Case "PH"
                    AddrArray(i) = "PENTHOUSE"
                Case "PKE"
                    AddrArray(i) = "PIKE"
                Case "PNE"
                    AddrArray(i) = "PINE"
                Case "PNES"
                    AddrArray(i) = "PINES"
                Case "PL"
                    AddrArray(i) = "PLACE"
                Case "PLN"
                    AddrArray(i) = "PLAIN"
                Case "PLNS"
                    AddrArray(i) = "PLAINS"
                Case "PLZ", "PLZA"
                    AddrArray(i) = "PLAZA"
                Case "PT"
                    AddrArray(i) = "POINT"
                Case "PTS"
                    AddrArray(i) = "POINTS"
                Case "PRT"
                    AddrArray(i) = "PORT"
                Case "PRTS"
                    AddrArray(i) = "PORTS"
                Case "PO", "P.O."
                    AddrArray(i) = "POST OFFICE"
                Case "PR", "PRR"
                    AddrArray(i) = "PRAIRIE"
                Case "RAD", "RADIEL", "RADL"
                    AddrArray(i) = "RADIAL"
                Case "RANCH ROAD", "RM", "R.M", "RM.", "R.M."
                    AddrArray(i) = "RANCH TO MARKET ROAD"
                Case "RNCH"
                    AddrArray(i) = "RANCH"
                Case "RNCHS"
                    AddrArray(i) = "RANCHES"
                Case "RPD"
                    AddrArray(i) = "RAPID"
                Case "RPDS"
                    AddrArray(i) = "RAPIDS"
                Case "RST"
                    AddrArray(i) = "REST"
                Case "RDG", "RDGE"
                    AddrArray(i) = "RIDGE"
                Case "RDGS"
                    AddrArray(i) = "RIDGES"
                Case "R", "RIV", "RIVR", "RVR"
                    AddrArray(i) = "RIVER"
                Case "RD"
                    AddrArray(i) = "ROAD"
                Case "RDS"
                    AddrArray(i) = "ROADS"
                Case "RM"
                    AddrArray(i) = "ROOM"
                Case "RTE"
                    AddrArray(i) = "ROUTE"
                Case "RR"
                    AddrArray(i) = "RURAL ROUTE"
                Case "ST,", "STR", "STRT"
                    AddrArray(i) = "STREET"
                Case "STS"
                    AddrArray(i) = "STREETS"
                Case "ST.", "ST"
                    SaintOrStreet = MsgBox("Does the 'S' in the following address stand for 'Street'? If no is selected, 'Saint' will be used instead." & vbCrLf & ActiveCell.Value, vbQuestion + vbYesNo + vbDefaultButton2, "Saint or Street")
                    If SaintOrStreet = vbYes Then
                        AddrArray(i) = "STREET"
                    Else
                        AddrArray(i) = "SAINT"
                    End If
                Case "S"
                    SouthOrStreet = MsgBox("Does the 'S' in the following address stand for 'Street'? If no is selected, 'South' will be used instead." & vbCrLf & ActiveCell.Value, vbQuestion + vbYesNo + vbDefaultButton2, "Street or South?")
                    If SouthOrStreet = vbYes Then
                        AddrArray(i) = "STREET"
                    Else
                        AddrArray(i) = "SOUTH"
                    End If
                Case "SHL"
                    AddrArray(i) = "SHOAL"
                Case "SHLS"
                    AddrArray(i) = "SHOALS"
                Case "SHOAR", "SHR"
                    AddrArray(i) = "SHORE"
                Case "SHOARS", "SHRS"
                    AddrArray(i) = "SHORES"
                Case "SKWY"
                    AddrArray(i) = "SKYWAY"
                Case "SE"
                    AddrArray(i) = "SOUTHEAST"
                Case "SW"
                    AddrArray(i) = "SOUTHWEST"
                Case "SPC"
                    AddrArray(i) = "SPACE"
                Case "SPG", "SPNG", "SPRNG"
                    AddrArray(i) = "SPRING"
                Case "SPGS", "SPNGS", "SPRNGS"
                    AddrArray(i) = "SPRINGS"
                Case "SQ", "SQR", "SQRE", "SQU"
                    AddrArray(i) = "SQUARE"
                Case "SQRS", "SQS"
                    AddrArray(i) = "SQUARES"
                Case "STA", "STATN", "STN"
                    AddrArray(i) = "STATION"
                Case "STRA", "STRAV", "STRAVEN", "STRAVN", "STRVN", "STRVNUE"
                    AddrArray(i) = "STRAVENUE"
                Case "STREME", "STRM"
                    AddrArray(i) = "STREAM"
                Case "STE"
                    AddrArray(i) = "SUITE"
                Case "SMT", "SUMIT", "SUMITT"
                    AddrArray(i) = "SUMMIT"
                Case "TCE", "TER", "TERR"
                    AddrArray(i) = "TERRACE"
                Case "THWY", "TRWY"
                    AddrArray(i) = "THROUGHWAY"
                Case "TRCE"
                    AddrArray(i) = "TRACE"
                Case "TRAK", "TRK"
                    AddrArray(i) = "TRACK"
                Case "TRKS"
                    AddrArray(i) = "TRACKS"
                Case "TRFY"
                    AddrArray(i) = "TRAFFICWAY"
                Case "TR", "TRL"
                    AddrArray(i) = "TRAIL"
                Case "TRLS"
                    AddrArray(i) = "TRAILS"
                Case "TRLR"
                    AddrArray(i) = "TRAILER"
                Case "TRLRS"
                    AddrArray(i) = "TRAILERS"
                Case "TUNEL", "TUNL", "TUNLS", "TUNNL"
                    AddrArray(i) = "TUNNEL"
                Case "TPK", "TPKE", "TRNPK", "TURNPK"
                    AddrArray(i) = "TURNPIKE"
                Case "UPAS"
                    AddrArray(i) = "UNDERPASS"
                Case "UN"
                    AddrArray(i) = "UNION"
                Case "UNS"
                    AddrArray(i) = "UNIONS"
                Case "UPPR"
                    AddrArray(i) = "UPPER"
                Case "WALK"
                    AddrArray(i) = "WALKS"
                Case "VALLY", "VLLY", "VLY"
                    AddrArray(i) = "VALLEY"
                Case "VLYS"
                    AddrArray(i) = "VALLEYS"
                Case "WTR"
                    AddrArray(i) = "WATERS"
                Case "WY"
                    AddrArray(i) = "WAY"
                Case "WL"
                    AddrArray(i) = "WELL"
                Case "WLS"
                    AddrArray(i) = "WELLS"
                Case "W"
                    AddrArray(i) = "WEST"
                Case "VDCT", "VIA", "VIADCT"
                    AddrArray(i) = "VIADUCT"
                Case "VW"
                    AddrArray(i) = "VIEW"
                Case "VWS"
                    AddrArray(i) = "VIEWS"
                Case "VILL", "VILLAG", "VILLG", "VLG"
                    AddrArray(i) = "VILLAGE"
                Case "VLGS"
                    AddrArray(i) = "VILLAGES"
                Case "VL"
                    AddrArray(i) = "VILLE"
                Case "VIS", "VIST", "VST", "VSTA"
                    AddrArray(i) = "VISTA"
                Case " "
                    AddrArray(i) = ""
        End Select
        ModifiedAddr = Join(AddrArray, " ")
        ModifiedAddr = Application.WorksheetFunction.Trim(ModifiedAddr)
        Next i
        ActiveCell.Value = ModifiedAddr
    Next x
End Sub