Attribute VB_Name = "Street_Name_Unabbreviator"
'=================================================================================================================================================
' This function works by going through a table that must be named "abbreviationsTable" with its upper left corner placed at Cell A1.
' The function then goes through all rows in the table and replaces each abbreviated word with its full form according to the select case below.
' To see the latest source code for this project, please visit https://github.com/theAwesomeFufuman/VBA-Street-Name-unabbreviator
'=================================================================================================================================================
Sub GeoCode()
    Range("A1").Activate
    Dim tbl As ListObject
    Dim x As Long
    Dim Address As String
    Dim AddrArray() As String
    Dim ModifiedAddr As String
    Dim SouthOrStreet As Integer
    Dim SaintOrStreet As Integer
    Dim EastOrE As Integer
    Set tbl = ActiveSheet.ListObjects("abbreviationsTable")
    'Loop Through Each DataBody Row in Table
    For x = 1 To tbl.ListRows.Count
        ActiveCell.Offset(1, 0).Activate
        AddrArray = Split(ActiveCell.Value, " ")
        For i = 0 To UBound(AddrArray)
            Select Case AddrArray(i)
                Case "ALLEE"
                    AddrArray(i) = "ALLEY"
                Case "ALLY"
                    AddrArray(i) = "ALLEY"
                Case "ALY"
                    AddrArray(i) = "ALLEY"
                Case "ANEX"
                    AddrArray(i) = "ANNEX"
                Case "ANX"
                    AddrArray(i) = "ANNEX"
                Case "APT"
                    AddrArray(i) = "APARTMENT"
                Case "ARC"
                    AddrArray(i) = "ARCADE"
                Case "AV"
                    AddrArray(i) = "AVENUE"
                Case "AVE"
                    AddrArray(i) = "AVENUE"
                Case "AVE,"
                    AddrArray(i) = "AVENUE"
                Case "Ave"
                    AddrArray(i) = "AVENUE"
                Case "AVEA"
                    AddrArray(i) = "AVENUE"
                Case "AVEN"
                    AddrArray(i) = "AVENUE"
                Case "AVENU"
                    AddrArray(i) = "AVENUE"
                Case "AVN"
                    AddrArray(i) = "AVENUE"
                Case "AVNUE"
                    AddrArray(i) = "AVENUE"
                Case "BSMT"
                    AddrArray(i) = "BASEMENT"
                Case "BAYOO"
                    AddrArray(i) = "BAYOU"
                Case "BYU"
                    AddrArray(i) = "BAYOU"
                Case "BCH"
                    AddrArray(i) = "BEACH"
                Case "BND"
                    AddrArray(i) = "BEND"
                Case "BLF"
                    AddrArray(i) = "BLUFF"
                Case "BLUF"
                    AddrArray(i) = "BLUFF"
                Case "BLFS"
                    AddrArray(i) = "BLUFFS"
                Case "BOT"
                    AddrArray(i) = "BOTTOM"
                Case "BOTTM"
                    AddrArray(i) = "BOTTOM"
                Case "BTM"
                    AddrArray(i) = "BOTTOM"
                Case "BLVD"
                    AddrArray(i) = "BOULEVARD"
                Case "BOUL"
                    AddrArray(i) = "BOULEVARD"
                Case "BOULV"
                    AddrArray(i) = "BOULEVARD"
                Case "BVD"
                    AddrArray(i) = "BOULEVARD"
                Case "BR"
                    AddrArray(i) = "BRANCH"
                Case "BRNCH"
                    AddrArray(i) = "BRANCH"
                Case "BRDGE"
                    AddrArray(i) = "BRIDGE"
                Case "BRG"
                    AddrArray(i) = "BRIDGE"
                Case "Bdwy"
                    AddrArray(i) = "Broadway"
                Case "BRK"
                    AddrArray(i) = "BROOK"
                Case "BRKS"
                    AddrArray(i) = "BROOKS"
                Case "BLDG"
                    AddrArray(i) = "BUILDING"
                Case "BG"
                    AddrArray(i) = "BURG"
                Case "BGS"
                    AddrArray(i) = "BURGS"
                Case "BYP"
                    AddrArray(i) = "BYPASS"
                Case "BYPA"
                    AddrArray(i) = "BYPASS"
                Case "BYPAS"
                    AddrArray(i) = "BYPASS"
                Case "BYPS"
                    AddrArray(i) = "BYPASS"
                Case "CMP"
                    AddrArray(i) = "CAMP"
                Case "CP"
                    AddrArray(i) = "CAMP"
                Case "CANYN"
                    AddrArray(i) = "CANYON"
                Case "CNYN"
                    AddrArray(i) = "CANYON"
                Case "CYN"
                    AddrArray(i) = "CANYON"
                Case "CPE"
                    AddrArray(i) = "CAPE"
                Case "CAUSWA"
                    AddrArray(i) = "CAUSEWAY"
                Case "CSWY"
                    AddrArray(i) = "CAUSEWAY"
                Case "CEN"
                    AddrArray(i) = "CENTER"
                Case "CENT"
                    AddrArray(i) = "CENTER"
                Case "CENTR"
                    AddrArray(i) = "CENTER"
                Case "CNTER"
                    AddrArray(i) = "CENTER"
                Case "CNTR"
                    AddrArray(i) = "CENTER"
                Case "CTR"
                    AddrArray(i) = "CENTER"
                Case "CTRS"
                    AddrArray(i) = "CENTERS"
                Case "CIR"
                    AddrArray(i) = "CIRCLE"
                Case "CIRC"
                    AddrArray(i) = "CIRCLE"
                Case "CIRCL"
                    AddrArray(i) = "CIRCLE"
                Case "CRCL"
                    AddrArray(i) = "CIRCLE"
                Case "CRCLE"
                    AddrArray(i) = "CIRCLE"
                Case "CIRS"
                    AddrArray(i) = "CIRCLES"
                Case "Cct"
                    AddrArray(i) = "Circuit"
                Case "CLF"
                    AddrArray(i) = "CLIFF"
                Case "CLFS"
                    AddrArray(i) = "CLIFF"
                Case "Cl"
                    AddrArray(i) = "Close"
                Case "CLB"
                    AddrArray(i) = "CLUB"
                Case "CMN"
                    AddrArray(i) = "COMMON"
                Case "CMNS"
                    AddrArray(i) = "COMMONS"
                Case "COR"
                    AddrArray(i) = "CORNER"
                Case "CRN"
                    AddrArray(i) = "CORNER"
                Case "CORS"
                    AddrArray(i) = "CORNERS"
                Case "CR"
                    AddrArray(i) = "COUNTRY ROAD"
                Case "C.R"
                    AddrArray(i) = "COUNTRY ROAD"
                Case "CR."
                    AddrArray(i) = "COUNTRY ROAD"
                Case "C.R."
                    AddrArray(i) = "COUNTRY ROAD"
                Case "CRSE"
                    AddrArray(i) = "COURSE"
                Case "CT"
                    AddrArray(i) = "COURT"
                Case "CTS"
                    AddrArray(i) = "COURTS"
                Case "CV"
                    AddrArray(i) = "COVE"
                Case "CVS"
                    AddrArray(i) = "COVES"
                Case "CRK"
                    AddrArray(i) = "CREEK"
                Case "CRES"
                    AddrArray(i) = "CRESCENT"
                Case "CRSENT"
                    AddrArray(i) = "CRESCENT"
                Case "CRSNT"
                    AddrArray(i) = "CRESCENT"
                Case "CRST"
                    AddrArray(i) = "CREST"
                Case "CRSSNG"
                    AddrArray(i) = "CROSSING"
                Case "XING"
                    AddrArray(i) = "CROSSING"
                Case "XRD"
                    AddrArray(i) = "CROSSROAD"
                Case "XRDS"
                    AddrArray(i) = "CROSSROADS"
                Case "CDS"
                    AddrArray(i) = "CUL-DE-SAC"
                Case "CURV"
                    AddrArray(i) = "CURVE"
                Case "DL"
                    AddrArray(i) = "DALE"
                Case "DM"
                    AddrArray(i) = "DAM"
                Case "DEPT"
                    AddrArray(i) = "DEPARTMENT"
                Case "DIV"
                    AddrArray(i) = "DIVIDE"
                Case "DV"
                    AddrArray(i) = "DIVIDE"
                Case "DVD"
                    AddrArray(i) = "DIVIDE"
                Case "DIRVE"
                    AddrArray(i) = "DRIVE"
                Case "DR"
                    AddrArray(i) = "DRIVE"
                Case "DR,"
                    AddrArray(i) = "DRIVE"
                Case "DRIV"
                    AddrArray(i) = "DRIVE"
                Case "DRV"
                    AddrArray(i) = "DRIVE"
                Case "DRS"
                    AddrArray(i) = "DRIVES"
                Case "E"
                    EastOrE = MsgBox("Does the 'E' in the following address stand for 'East'? If no is selected, no change will be made." & vbCrLf & ActiveCell.Value, vbQuestion + vbYesNo + vbDefaultButton2, "East or E")
                    If EastOrE = vbYes Then
                        AddrArray(i) = "EAST"
                    End If
                Case "ESP"
                    AddrArray(i) = "ESPLANADE"
                Case "EST"
                    AddrArray(i) = "ESTATE"
                Case "ESTS"
                    AddrArray(i) = "ESTATES"
                Case "EXP"
                    AddrArray(i) = "EXPRESSWAY"
                Case "EXPR"
                    AddrArray(i) = "EXPRESSWAY"
                Case "EXPRESS"
                    AddrArray(i) = "EXPRESSWAY"
                Case "EXPW"
                    AddrArray(i) = "EXPRESSWAY"
                Case "EXPWY"
                    AddrArray(i) = "EXPRESSWAY"
                Case "EXPY"
                    AddrArray(i) = "EXPRESSWAY"
                Case "EXT"
                    AddrArray(i) = "EXTENSION"
                Case "EXTN"
                    AddrArray(i) = "EXTENSION"
                Case "EXTNSN"
                    AddrArray(i) = "EXTENSION"
                Case "EXTS"
                    AddrArray(i) = "EXTENSIONS"
                Case "FLS"
                    AddrArray(i) = "FALLS"
                Case "FRRY"
                    AddrArray(i) = "FERRY"
                Case "FRY"
                    AddrArray(i) = "FERRY"
                Case "FLD"
                    AddrArray(i) = "FIELD"
                Case "FLDS"
                    AddrArray(i) = "FIELDS"
                Case "FLT"
                    AddrArray(i) = "FLAT"
                Case "FLTS"
                    AddrArray(i) = "FLATS"
                Case "FL"
                    AddrArray(i) = "FLOOR"
                Case "FM"
                    AddrArray(i) = "FARM TO MARKET ROAD"
                Case "F.M"
                    AddrArray(i) = "FARM TO MARKET ROAD"
                Case "FM."
                    AddrArray(i) = "FARM TO MARKET ROAD"
                Case "F.M."
                    AddrArray(i) = "FARM TO MARKET ROAD"
                Case "FRD"
                    AddrArray(i) = "FORD"
                Case "FRDS"
                    AddrArray(i) = "FORDS"
                Case "FRST"
                    AddrArray(i) = "FOREST"
                Case "FORG"
                    AddrArray(i) = "FORGE"
                Case "FRG"
                    AddrArray(i) = "FORGE"
                Case "FRGS"
                    AddrArray(i) = "FORGES"
                Case "FRK"
                    AddrArray(i) = "FORK"
                Case "FRKS"
                    AddrArray(i) = "FORKS"
                Case "FRT"
                    AddrArray(i) = "FORT"
                Case "FT"
                    AddrArray(i) = "FORT"
                Case "FREEWY"
                    AddrArray(i) = "FREEWAY"
                Case "FRWAY"
                    AddrArray(i) = "FREEWAY"
                Case "FRWY"
                    AddrArray(i) = "FREEWAY"
                Case "FWY"
                    AddrArray(i) = "FREEWAY"
                Case "FRNT"
                    AddrArray(i) = "FRONT"
                Case "GARDN"
                    AddrArray(i) = "GARDEN"
                Case "GDN"
                    AddrArray(i) = "GARDEN"
                Case "GRDEN"
                    AddrArray(i) = "GARDEN"
                Case "GRDN"
                    AddrArray(i) = "GARDEN"
                Case "GDNS"
                    AddrArray(i) = "GARDENS"
                Case "GRDNS"
                    AddrArray(i) = "GARDENS"
                Case "GATEWY"
                    AddrArray(i) = "GATEWAY"
                Case "GATWAY"
                    AddrArray(i) = "GATEWAY"
                Case "GTWAY"
                    AddrArray(i) = "GATEWAY"
                Case "GTWY"
                    AddrArray(i) = "GATEWAY"
                Case "GLN"
                    AddrArray(i) = "GLEN"
                Case "GLNS"
                    AddrArray(i) = "GLENS"
                Case "GRN"
                    AddrArray(i) = "GREEN"
                Case "GRNS"
                    AddrArray(i) = "GREENS"
                Case "GR"
                    AddrArray(i) = "GROVE"
                Case "GROV"
                    AddrArray(i) = "GROVE"
                Case "GRV"
                    AddrArray(i) = "GROVE"
                Case "GRVS"
                    AddrArray(i) = "GROVES"
                Case "HNGR"
                    AddrArray(i) = "HANGER"
                Case "HARB"
                    AddrArray(i) = "HARBOR"
                Case "HARBR"
                    AddrArray(i) = "HARBOR"
                Case "HBR"
                    AddrArray(i) = "HARBOR"
                Case "HRBOR"
                    AddrArray(i) = "HARBOR"
                Case "HBRS"
                    AddrArray(i) = "HARBORS"
                Case "HVN"
                    AddrArray(i) = "HAVEN"
                Case "HT"
                    AddrArray(i) = "HEIGHT"
                Case "HTS"
                    AddrArray(i) = "HEIGHTS"
                Case "HIGHWY"
                    AddrArray(i) = "HIGHWAY"
                Case "HIWAY"
                    AddrArray(i) = "HIGHWAY"
                Case "HIWY"
                    AddrArray(i) = "HIGHWAY"
                Case "HWAY"
                    AddrArray(i) = "HIGHWAY"
                Case "HWY"
                    AddrArray(i) = "HIGHWAY"
                Case "HL"
                    AddrArray(i) = "HILL"
                Case "HLS"
                    AddrArray(i) = "HILLS"
                Case "HLLW"
                    AddrArray(i) = "HOLLOW"
                Case "HOLW"
                    AddrArray(i) = "HOLLOW"
                Case "HOLWS"
                    AddrArray(i) = "HOLLOWS"
                Case "INFO"
                    AddrArray(i) = "INFORMATION"
                Case "INLT"
                    AddrArray(i) = "INLET"
                Case "INTL"
                    AddrArray(i) = "INTERNATIONAL"
                Case "IS"
                    AddrArray(i) = "ISLAND"
                Case "ISL"
                    AddrArray(i) = "ISLAND"
                Case "ISLND"
                    AddrArray(i) = "ISLAND"
                Case "ISLNDS"
                    AddrArray(i) = "ISLANDS"
                Case "ISS"
                    AddrArray(i) = "ISLANDS"
                Case "IL"
                    AddrArray(i) = "ISLE"
                Case "JCT"
                    AddrArray(i) = "JUNCTION"
                Case "JCTION"
                    AddrArray(i) = "JUNCTION"
                Case "JCTN"
                    AddrArray(i) = "JUNCTION"
                Case "JNC"
                    AddrArray(i) = "JUNCTION"
                Case "JUNCTN"
                    AddrArray(i) = "JUNCTION"
                Case "JUNCTON"
                    AddrArray(i) = "JUNCTION"
                Case "JCTNS"
                    AddrArray(i) = "JUNCTIONS"
                Case "JCTS"
                    AddrArray(i) = "JUNCTIONS"
                Case "KY"
                    AddrArray(i) = "KEY"
                Case "KYS"
                    AddrArray(i) = "KEYS"
                Case "KNL"
                    AddrArray(i) = "KNOLL"
                Case "KNOL"
                    AddrArray(i) = "KNOLL"
                Case "KNLS"
                    AddrArray(i) = "KNOLLS"
                Case "LK"
                    AddrArray(i) = "LAKE"
                Case "LKS"
                    AddrArray(i) = "LAKES"
                Case "LNDG"
                    AddrArray(i) = "LANDING"
                Case "LNDNG"
                    AddrArray(i) = "LANDING"
                Case "LN"
                    AddrArray(i) = "LANE"
                Case "LGT"
                    AddrArray(i) = "LIGHT"
                Case "LGTS"
                    AddrArray(i) = "LIGHTS"
                Case "LF"
                    AddrArray(i) = "LOAF"
                Case "LBBY"
                    AddrArray(i) = "LOBBY"
                Case "LCK"
                    AddrArray(i) = "LOCK"
                Case "LCKS"
                    AddrArray(i) = "LOCKS"
                Case "LDG"
                    AddrArray(i) = "LODGE"
                Case "LDGE"
                    AddrArray(i) = "LODGE"
                Case "LODG"
                    AddrArray(i) = "LODGE"
                Case "LP"
                    AddrArray(i) = "LOOP"
                Case "LOWR"
                    AddrArray(i) = "LOWER"
                Case "MNR"
                    AddrArray(i) = "MANOR"
                Case "MNRS"
                    AddrArray(i) = "MANORS"
                Case "MDW"
                    AddrArray(i) = "MEADOW"
                Case "MDWS"
                    AddrArray(i) = "MEADOWS"
                Case "MEDOWS"
                    AddrArray(i) = "MEADOWS"
                Case "ML"
                    AddrArray(i) = "MILL"
                Case "MLS"
                    AddrArray(i) = "MILLS"
                Case "MISSN"
                    AddrArray(i) = "MISSION"
                Case "MSN"
                    AddrArray(i) = "MISSION"
                Case "MSSN"
                    AddrArray(i) = "MISSION"
                Case "MTWY"
                    AddrArray(i) = "MOTORWAY"
                Case "MNT"
                    AddrArray(i) = "MOUNT"
                Case "MT"
                    AddrArray(i) = "MOUNT"
                Case "MNTAIN"
                    AddrArray(i) = "MOUNTAIN"
                Case "MNTN"
                    AddrArray(i) = "MOUNTAIN"
                Case "MOUNTIN"
                    AddrArray(i) = "MOUNTAIN"
                Case "MTIN"
                    AddrArray(i) = "MOUNTAIN"
                Case "MTN"
                    AddrArray(i) = "MOUNTAIN"
                Case "MNTNS"
                    AddrArray(i) = "MOUNTAINS"
                Case "MTNS"
                    AddrArray(i) = "MOUNTAINS"
                Case "NATL"
                    AddrArray(i) = "NATIONAL"
                Case "NCK"
                    AddrArray(i) = "NECK"
                Case "N"
                    AddrArray(i) = "NORTH"
                Case "NE"
                    AddrArray(i) = "NORTHEAST"
                Case "NW"
                    AddrArray(i) = "NORTHWEST"
                Case "OFC"
                    AddrArray(i) = "OFFICE"
                Case "ORCH"
                    AddrArray(i) = "ORCHARD"
                Case "ORCHRD"
                    AddrArray(i) = "ORCHARD"
                Case "OVL"
                    AddrArray(i) = "OVAL"
                Case "OPAS"
                    AddrArray(i) = "OVERPASS"
                Case "PDE"
                    AddrArray(i) = "PARADE"
                Case "PK"
                    AddrArray(i) = "PARK"
                Case "PRK"
                    AddrArray(i) = "PARK"
                Case "PKS"
                    AddrArray(i) = "PARKS"
                Case "PARKWY"
                    AddrArray(i) = "PARKWAY"
                Case "PKWAY"
                    AddrArray(i) = "PARKWAY"
                Case "PKWY"
                    AddrArray(i) = "PARKWAY"
                Case "PKY"
                    AddrArray(i) = "PARKWAY"
                Case "PKWYS"
                    AddrArray(i) = "PARKWAYS"
                Case "PSGE"
                    AddrArray(i) = "PASSAGE"
                Case "PATH"
                    AddrArray(i) = "PATHS"
                Case "PH"
                    AddrArray(i) = "PENTHOUSE"
                Case "PKE"
                    AddrArray(i) = "PIKE"
                Case "PNE"
                    AddrArray(i) = "PINE"
                Case "PNES"
                    AddrArray(i) = "PINES"
                Case "PL"
                    AddrArray(i) = "PLACE"
                Case "PLN"
                    AddrArray(i) = "PLAIN"
                Case "PLNS"
                    AddrArray(i) = "PLAINS"
                Case "PLZ"
                    AddrArray(i) = "PLAZA"
                Case "PLZA"
                    AddrArray(i) = "PLAZA"
                Case "PT"
                    AddrArray(i) = "POINT"
                Case "PTS"
                    AddrArray(i) = "POINTS"
                Case "PRT"
                    AddrArray(i) = "PORT"
                Case "PRTS"
                    AddrArray(i) = "PORTS"
                Case "PO"
                    AddrArray(i) = "POST OFFICE"
                Case "PR"
                    AddrArray(i) = "PRAIRIE"
                Case "PRR"
                    AddrArray(i) = "PRAIRIE"
                Case "RAD"
                    AddrArray(i) = "RADIAL"
                Case "RADIEL"
                    AddrArray(i) = "RADIAL"
                Case "RADL"
                    AddrArray(i) = "RADIAL"
                Case "RANCH ROAD"
                    AddrArray(i) = "RANCH TO MARKET ROAD"
                Case "RM"
                    AddrArray(i) = "RANCH TO MARKET ROAD"
                Case "R.M"
                    AddrArray(i) = "RANCH TO MARKET ROAD"
                Case "RM."
                    AddrArray(i) = "RANCH TO MARKET ROAD"
                Case "R.M."
                    AddrArray(i) = "RANCH TO MARKET ROAD"
                Case "RNCH"
                    AddrArray(i) = "RANCH"
                Case "RNCHS"
                    AddrArray(i) = "RANCHES"
                Case "RPD"
                    AddrArray(i) = "RAPID"
                Case "RPDS"
                    AddrArray(i) = "RAPIDS"
                Case "RST"
                    AddrArray(i) = "REST"
                Case "RDG"
                    AddrArray(i) = "RIDGE"
                Case "RDGE"
                    AddrArray(i) = "RIDGE"
                Case "RDGS"
                    AddrArray(i) = "RIDGES"
                Case "R"
                    AddrArray(i) = "RIVER"
                Case "RIV"
                    AddrArray(i) = "RIVER"
                Case "RIVR"
                    AddrArray(i) = "RIVER"
                Case "RVR"
                    AddrArray(i) = "RIVER"
                Case "RD"
                    AddrArray(i) = "ROAD"
                Case "RDS"
                    AddrArray(i) = "ROADS"
                Case "RM"
                    AddrArray(i) = "ROOM"
                Case "RTE"
                    AddrArray(i) = "ROUTE"
                Case "RR"
                    AddrArray(i) = "RURAL ROUTE"
                Case "ST."
                    SaintOrStreet = MsgBox("Does the 'S' in the following address stand for 'Street'? If no is selected, 'Saint will be used instead'." & vbCrLf & ActiveCell.Value, vbQuestion + vbYesNo + vbDefaultButton2, "Saint or Street")
                    If SaintOrStreet = vbYes Then
                        AddrArray(i) = "STREET"
                    Else
                        AddrArray(i) = "SAINT"
                    End If
                Case "ST"
                    SaintOrStreet = MsgBox("Does the 'S' in the following address stand for 'Street'? If no is selected, 'Saint will be used instead'." & vbCrLf & ActiveCell.Value, vbQuestion + vbYesNo + vbDefaultButton2, "Saint or Street")
                    If SaintOrStreet = vbYes Then
                        AddrArray(i) = "STREET"
                    Else
                        AddrArray(i) = "SAINT"
                    End If
                Case "SHL"
                    AddrArray(i) = "SHOAL"
                Case "SHLS"
                    AddrArray(i) = "SHOALS"
                Case "SHOAR"
                    AddrArray(i) = "SHORE"
                Case "SHR"
                    AddrArray(i) = "SHORE"
                Case "SHOARS"
                    AddrArray(i) = "SHORES"
                Case "SHRS"
                    AddrArray(i) = "SHORES"
                Case "SKWY"
                    AddrArray(i) = "SKYWAY"
                Case "S"
                    SouthOrStreet = MsgBox("Does the 'S' in the following address stand for 'Street'? If no is selected, 'South' will be used instead." & vbCrLf & ActiveCell.Value, vbQuestion + vbYesNo + vbDefaultButton2, "Street or South?")
                    If SouthOrStreet = vbYes Then
                        AddrArray(i) = "STREET"
                    Else
                        AddrArray(i) = "SOUTH"
                    End If
                Case "SE"
                    AddrArray(i) = "SOUTHEAST"
                Case "SW"
                    AddrArray(i) = "SOUTHWEST"
                Case "SPC"
                    AddrArray(i) = "SPACE"
                Case "SPG"
                    AddrArray(i) = "SPRING"
                Case "SPNG"
                    AddrArray(i) = "SPRING"
                Case "SPRNG"
                    AddrArray(i) = "SPRING"
                Case "SPGS"
                    AddrArray(i) = "SPRINGS"
                Case "SPNGS"
                    AddrArray(i) = "SPRINGS"
                Case "SPRNGS"
                    AddrArray(i) = "SPRINGS"
                Case "SQ"
                    AddrArray(i) = "SQUARE"
                Case "SQR"
                    AddrArray(i) = "SQUARE"
                Case "SQRE"
                    AddrArray(i) = "SQUARE"
                Case "SQU"
                    AddrArray(i) = "SQUARE"
                Case "SQRS"
                    AddrArray(i) = "SQUARES"
                Case "SQS"
                    AddrArray(i) = "SQUARES"
                Case "ST,"
                    AddrArray(i) = "STREET"
                Case "STA"
                    AddrArray(i) = "STATION"
                Case "STATN"
                    AddrArray(i) = "STATION"
                Case "STN"
                    AddrArray(i) = "STATION"
                Case "STRA"
                    AddrArray(i) = "STRAVENUE"
                Case "STRAV"
                    AddrArray(i) = "STRAVENUE"
                Case "STRAVEN"
                    AddrArray(i) = "STRAVENUE"
                Case "STRAVN"
                    AddrArray(i) = "STRAVENUE"
                Case "STRVN"
                    AddrArray(i) = "STRAVENUE"
                Case "STRVNUE"
                    AddrArray(i) = "STRAVENUE"
                Case "STREME"
                    AddrArray(i) = "STREAM"
                Case "STRM"
                    AddrArray(i) = "STREAM"
                Case "STR"
                    AddrArray(i) = "STREET"
                Case "STRT"
                    AddrArray(i) = "STREET"
                Case "STS"
                    AddrArray(i) = "STREETS"
                Case "STE"
                    AddrArray(i) = "SUITE"
                Case "SMT"
                    AddrArray(i) = "SUMMIT"
                Case "SUMIT"
                    AddrArray(i) = "SUMMIT"
                Case "SUMITT"
                    AddrArray(i) = "SUMMIT"
                Case "TCE"
                    AddrArray(i) = "TERRACE"
                Case "TER"
                    AddrArray(i) = "TERRACE"
                Case "TERR"
                    AddrArray(i) = "TERRACE"
                Case "THWY"
                    AddrArray(i) = "THROUGHWAY"
                Case "TRWY"
                    AddrArray(i) = "THROUGHWAY"
                Case "TRCE"
                    AddrArray(i) = "TRACE"
                Case "TRACE"
                    AddrArray(i) = "TRACES"
                Case "TRAK"
                    AddrArray(i) = "TRACK"
                Case "TRK"
                    AddrArray(i) = "TRACK"
                Case "TRKS"
                    AddrArray(i) = "TRACKS"
                Case "TRFY"
                    AddrArray(i) = "TRAFFICWAY"
                Case "TR"
                    AddrArray(i) = "TRAIL"
                Case "TRL"
                    AddrArray(i) = "TRAIL"
                Case "TRLS"
                    AddrArray(i) = "TRAILS"
                Case "TRLR"
                    AddrArray(i) = "TRAILER"
                Case "TRLRS"
                    AddrArray(i) = "TRAILERS"
                Case "TUNEL"
                    AddrArray(i) = "TUNNEL"
                Case "TUNL"
                    AddrArray(i) = "TUNNEL"
                Case "TUNLS"
                    AddrArray(i) = "TUNNEL"
                Case "TUNNL"
                    AddrArray(i) = "TUNNEL"
                Case "TPK"
                    AddrArray(i) = "TURNPIKE"
                Case "TPKE"
                    AddrArray(i) = "TURNPIKE"
                Case "TRNPK"
                    AddrArray(i) = "TURNPIKE"
                Case "TURNPK"
                    AddrArray(i) = "TURNPIKE"
                Case "UPAS"
                    AddrArray(i) = "UNDERPASS"
                Case "UN"
                    AddrArray(i) = "UNION"
                Case "UNS"
                    AddrArray(i) = "UNIONS"
                Case "UPPR"
                    AddrArray(i) = "UPPER"
                Case "WALK"
                    AddrArray(i) = "WALKS"
                Case "VALLY"
                    AddrArray(i) = "VALLEY"
                Case "VLLY"
                    AddrArray(i) = "VALLEY"
                Case "VLY"
                    AddrArray(i) = "VALLEY"
                Case "VLYS"
                    AddrArray(i) = "VALLEYS"
                Case "WTR"
                    AddrArray(i) = "WATERS"
                Case "WY"
                    AddrArray(i) = "WAY"
                Case "WL"
                    AddrArray(i) = "WELL"
                Case "WLS"
                    AddrArray(i) = "WELL"
                Case "W"
                    AddrArray(i) = "WEST"
                Case "VDCT"
                    AddrArray(i) = "VIADUCT"
                Case "VIA"
                    AddrArray(i) = "VIADUCT"
                Case "VIADCT"
                    AddrArray(i) = "VIADUCT"
                Case "VW"
                    AddrArray(i) = "VIEW"
                Case "VWS"
                    AddrArray(i) = "VIEWS"
                Case "VILL"
                    AddrArray(i) = "VILLAGE"
                Case "VILLAG"
                    AddrArray(i) = "VILLAGE"
                Case "VILLG"
                    AddrArray(i) = "VILLAGE"
                Case "VLG"
                    AddrArray(i) = "VILLAGE"
                Case "VLGS"
                    AddrArray(i) = "VILLAGES"
                Case "VL"
                    AddrArray(i) = "VILLE"
                Case "VIS"
                    AddrArray(i) = "VISTA"
                Case "VIST"
                    AddrArray(i) = "VISTA"
                Case "VST"
                    AddrArray(i) = "VISTA"
                Case "VSTA"
                    AddrArray(i) = "VISTA"
                Case " "
                    AddrArray(i) = ""
        End Select
        ModifiedAddr = Join(AddrArray, " ")
        ModifiedAddr = Application.WorksheetFunction.Trim(ModifiedAddr)
        Next i
        ActiveCell.Value = ModifiedAddr
    Next x
End Sub

